import { readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const MESSAGES_ROOT = path.join(process.cwd(), "src", "messages");
const OUTPUT_PATH = path.join(process.cwd(), "src", "lib", "i18n", "generated-locales.ts");
const PREFERRED_DEFAULT_LANGUAGE = "ja";

function detectLocales(): string[] {
  const rootStat = statSync(MESSAGES_ROOT, { throwIfNoEntry: false });
  if (!rootStat?.isDirectory()) {
    return [];
  }

  return readdirSync(MESSAGES_ROOT)
    .map((entryName) => path.join(MESSAGES_ROOT, entryName))
    .filter((entryPath) => statSync(entryPath).isDirectory())
    .map((entryPath) => path.basename(entryPath))
    .sort((a, b) => a.localeCompare(b));
}

function main() {
  const locales = detectLocales();
  if (locales.length === 0) {
    console.error(`[i18n:sync-locales] No locale directories found in ${MESSAGES_ROOT}`);
    process.exit(1);
  }

  const defaultLanguage = locales.includes(PREFERRED_DEFAULT_LANGUAGE)
    ? PREFERRED_DEFAULT_LANGUAGE
    : locales[0];

  const fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/i18n/generate-locales.ts
export const SUPPORTED_LANGUAGES = ${JSON.stringify(locales)} as const;
export const DEFAULT_LANGUAGE = ${JSON.stringify(defaultLanguage)} as const;
`;

  writeFileSync(OUTPUT_PATH, fileContent, "utf-8");
  console.log(
    `[i18n:sync-locales] Updated ${path.relative(process.cwd(), OUTPUT_PATH)} (${locales.join(", ")})`
  );
}

main();
