import { Metadata } from 'next';

import { getRequestLanguage } from '@/lib/i18n/server';
import PlanLocalClient from './PlanLocalClient';

export async function generateMetadata(): Promise<Metadata> {
  const language = await getRequestLanguage();
  return language === "ja"
    ? {
        title: '旅行プラン結果',
        description: 'AIが生成したあなただけの旅行プラン結果です。',
      }
    : {
        title: 'Trip Plan Result',
        description: 'Your personalized travel plan generated by AI.',
      };
}

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function PlanLocalPage({ params }: PageProps) {
  const { id } = await params;

  return <PlanLocalClient localId={id} />;
}
