import { Metadata } from "next";
import PlanClient from "./PlanClient";
import { getRequestLanguage } from "@/lib/i18n/server";

export const maxDuration = 120;

export async function generateMetadata(): Promise<Metadata> {
  const language = await getRequestLanguage();
  return language === "ja"
    ? {
        title: "旅行プラン結果",
        description: "AIが生成したあなただけの旅行プラン結果です。",
      }
    : {
        title: "Trip Plan Result",
        description: "Your personalized travel plan generated by AI.",
      };
}

export default function PlanPage() {
  return <PlanClient />;
}
